### PR TITLE
Fix #689: bug in ZeroLengthPathIteration + cost estimate improvement in planner

### LINKED ISSUE #689: Zero or more path query is broken with some datasets
We've just upgraded our software from using Sesame 2.7.15 to rdf4j 2.1.2 and found that property paths (https://www.w3.org/TR/sparql11-property-paths/#path-language) that use * do not work with some datasets. I had trouble building up a dataset from scratch to reproduce the issue (it seemed to work on smaller datasets) so instead took the larger dataset that we did have that was showing the issue and have attached that (after scrambling some IP out of it). There are screen captures showing the steps to reproduce the issue and the dataset and queries.

We have been able to work around the issue by re-writing the query using a UNION clause, but have now found another query that doesn't seem to work, even after doing that. At this point we can't upgrade as we are not confident that the queries will continue to work correctly as the underlying dataset changes.

[rdf4j-bug.zip](https://github.com/eclipse/rdf4j/files/635373/rdf4j-bug.zip)

### PR DESCRIPTION
**Pull request by jeenbroekstra**
This PR addresses GitHub issue: #689 .

Briefly describe the changes proposed in this PR:

* QueryJoinOptimizer incorrectly reorganized joins involving ArbitraryLengthPaths due to too-low estimate of cost.
* cost estimate now based on store estimate of single statement pattern involving the ALP's subject and object, and an unknown predicate, times 2 (we estimate an ALP's path length will be at least 2). 
* Tested manually that the bug is specifically caused by the optimizer, not by the execution engine: if the optimizer is completely disabled, the engine does compute the correct query result.

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
Unfortunately this is problematic to write a regression test for as the bug is only apparent for sufficiently large datasets (in which case store statistics for individual statement patterns become significant enough to influence join order).

**Comment by ansell** [comment]
Adding a short test to https://github.com/eclipse/rdf4j/blob/master/testsuites/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ComplexSPARQLQueryTest.java#L1469 for /* patterns may still be useful (unless it is tested by another testsuite already) even if it doesn't trigger the bug.

Given the fix is adjusting a heuristically defined parameter, there may be other cases that aren't tested, but if you could programmatically generate a file that triggers it it may be useful.

What effect does turning off optimisation for property paths have?

**Comment by jeenbroekstra** [comment]
Good point re: the tests, I'll have a closer look. 

Turning off optimization simply leaves the original join order intact. The reordered join tree evaluates the ALP too early, which leaves several of its variables unbound. To be fair: this should still work regardless of how inefficient it is, so there may be a deeper cause that I haven't yet pinpointed.

**Comment by jeenbroekstra** [comment]
Found the root cause, a bug in ZeroLengthPathIteration (see latest commit). I'll work on some regression tests. I'll leave the statistics improvement in place as well.

File: core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIterationTest.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+			}
+		};
+		evaluator = new StrictEvaluationStrategy(ts, null);
+	}
+
+	@Test
+	public void testRetainInputBindings() {
+
+		MapBindingSet bindings = new MapBindingSet();
+		bindings.addBinding("a", RDF.FIRST);
```
Comment (ansell) [inline core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIterationTest.java]: Just to check I understand this, the regression test is that "a", which isn't otherwise involved in the zero length path, is still included in the bindings along with "x" and "y"

Comment (jeenbroekstra) [inline core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIterationTest.java]: Exactly. The problem was that ZeroLengthPathIteration, in a certain code path (namely when none of its involved variables have a binding), simply create a completely new BindingSet from scratch, omitting all the input bindings - which means it would effectively erase bindings insert by a VALUES clause. 

I'll add some comments to the test to make this clearer.

Comment (jeenbroekstra) [inline core/queryalgebra/evaluation/src/test/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/ZeroLengthPathIterationTest.java]: Btw this also explains why the problem was related to the statistics / dataset size: on smaller datasets the ZLP evaluation is pushed further down, resulting in its subject variable being given a fixed value - so it followed a different code path and didn't erase any bindings.
