### PR TITLE
Fix #220: search improvements

### LINKED ISSUE #220: search query evaluator is not able to get query string from Literal
Affected: rdf4j version _2.0M3_
Java: 1.8
Os: Ubuntu 16.04

In Lucene search query only direct _String_ is accepted, ie: `search:query "abc123"` works fine.
In case if the term is instance of Literal taken as result of other _atomic_ request it fails. For example:

```
prefix search: <http://www.openrdf.org/contrib/lucenesail#>
prefix y: <urn:raw:yeastract#>

select ?sub ?query (isLiteral(?query) as ?isLit) ?score where {
  [] y:Yeast_id ?query .
  ?sub search:matches [
  search:query ?query ;
  search:score ?score
  ] .
}
```

I have error:

```
Exception in thread "main" org.eclipse.rdf4j.query.QueryEvaluationException: Invalid Text Query: missing query string for Lucene query specification
    at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:59)
    at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
    at sparql$process_sparql_query.invokeStatic(sparql.clj:92)
    at sparql$process_sparql_query.invoke(sparql.clj:83)
    at sparql$_main$fn__652.invoke(sparql.clj:68)
    at sparql$_main.invokeStatic(sparql.clj:67)
    at sparql$_main.doInvoke(sparql.clj:47)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at sparql.main(Unknown Source)
Caused by: org.eclipse.rdf4j.sail.SailException: Invalid Text Query: missing query string for Lucene query specification
    at org.eclipse.rdf4j.sail.lucene.QuerySpecBuilder.failOrWarn(QuerySpecBuilder.java:203)
    at org.eclipse.rdf4j.sail.lucene.QuerySpecBuilder.process(QuerySpecBuilder.java:137)
    at org.eclipse.rdf4j.sail.lucene.LuceneSailConnection.evaluate(LuceneSailConnection.java:294)
    at org.eclipse.rdf4j.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:50)
    ... 14 more
```

`?query` is literal:

```
prefix search: <http://www.openrdf.org/contrib/lucenesail#>
prefix y: <urn:raw:yeastract#>

select ?query (isLiteral(?query) as ?isLit) where {
  [] y:Yeast_id ?query .

}
```

Gives:

```
query,isLit
Abf1,true
Abf2,true
Arr1,true
Put3,true
Rap1,true
```

### PR DESCRIPTION
**Pull request by pulquero**
This PR addresses GitHub issue: #220.

Briefly describe the changes proposed in this PR:
- Initial code for review and to demonstrate design. Currently missing support for all EvaluationModes and geo search, and better integration with existing SPIN stuff. These are pending outcome of feedback.

### CODE REVIEW

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QueryContext.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
+/*******************************************************************************
+ * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QueryContext.java]: This is the wrong license header for new files.

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QueryContextIteration.java [hunk 2]
```diff
@@ -0,0 +1,78 @@
+/*******************************************************************************
+ * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QueryContextIteration.java]: Ditto. Should just say "Copyright (c) 2015 Eclipse RDF4J contributors." Check the code template settings.

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QuerySpec.java [hunk 3]
```diff
@@ -54,6 +62,40 @@ public QuerySpec(StatementPattern matchesPattern, StatementPattern queryPattern,
 		this.subject = subject;
 		this.queryString = queryString;
 		this.propertyURI = propertyURI;
+		if (matchesPattern != null)
+			this.matchesVarName = matchesPattern.getSubjectVar().getName();
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/QuerySpec.java]: This is really minor, but we have an implicit agreement to _always_ use curly braces for if-statements, even if the body is only a single line.

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java [hunk 4]
```diff
@@ -252,6 +257,33 @@
...
+	/**
+	 * Eagerly evaluates any search queries and then delegates to the base SAIL.
+	 */
+	public static final String EAGER_EVALUATION_MODE = "eager";
+
+	/**
+	 * Uses the base SAIL along with an embedded SERVICE to perform query evaluation. The SERVICE is used to
+	 * evaluate extended query algebra nodes such as {@link TupleFunction}s.
+	 */
+	public static final String SERVICE_EVALUATION_MODE = "service";
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java]: So how would this SERVICE be specified? As part of the SPARQL query?

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java [hunk 5]
```diff
@@ -252,6 +257,33 @@
 	public static final String INCOMPLETE_QUERY_FAIL_KEY = "incompletequeryfail";
 
 	/**
+	 * Set this key to "false" to disable late evaluation of search queries.
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java]: Not sure I understand. Is this constant the name of the config property? If so what are its possible values?

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java [hunk 6]
```diff
@@ -252,6 +257,33 @@
...
+	 */
+	public static final String EVALUATION_MODE_KEY = "evaluationMode";
+
+	/**
+	 * Eagerly evaluates any search queries and then delegates to the base SAIL.
+	 */
+	public static final String EAGER_EVALUATION_MODE = "eager";
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java]: Isn't this the default mode of operation?

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java [hunk 7]
```diff
@@ -252,6 +257,33 @@
...
+	/**
+	 * Assumes the base SAIL supports an extended query algebra (e.g. {@link TupleFunction}s) and use it to
+	 * perform all query evaluation.
+	 */
+	public static final String NATIVE_EVALUATION_MODE = "native";
+
+	/**
+	 * Treats the base SAIL as a simple triple source and all the query evaluation is performed by this SAIL.
+	 */
+	public static final String TRIPLE_SOURCE_EVALUATION_MODE = "tripleSource";
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java]: I'm not really sure I understand how 'native' and 'tripleSource' evaluation modes compare to 'eager'.

File: core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java [hunk 8]
```diff
@@ -419,6 +459,40 @@ public void setIncompleteQueryFails(boolean incompleteQueryFails) {
 	}
 
 	/**
+	 * See EVALUATION_MODE_KEY parameter.
+	 */
+	public String getEvaluationMode() {
```
Comment (jeenbroekstra) [inline core/sail/fts/lucene-api/src/main/java/org/eclipse/rdf4j/sail/lucene/LuceneSail.java]: For clarity I think it might be good to create an `Enum` for the various Evaluation modes.

**Comment by jgrzebyta** [comment]
@pulquero  you can take "suit tests" from my branch with both the old solution and the spin-based one for issues #220 and #235 . 

Temporary I switched off (by `@Ignore`) complex tests and lest the simple one.

**Comment by pulquero** [comment]
Most spin magic properties evaluate in the other direction:
("Abf1" <http://www.openrdf.org/contrib/lucenesail#allMatches> <http://www.openrdf.org/contrib/lucenesail#score>) <http://www.openrdf.org/contrib/lucenesail#search> (?pred ?score) 

cf:

(?query "this" owl:Thing) spin:construct (?s ?p ?o)

However the spif functions are all the other way round. jena property functions are a mixture. I don't have any preference myself, is one way more readable than the other? Any other consideration?



   

 On Wednesday, 5 October 2016, 18:05, Jacek Grzebyta <notifications@github.com> wrote:
 

 @pulquero you can take "suit tests" from my branch with both the old solution and the spin-based one for issues #220 and #235 . Temporary I switched off (by @Ignore) complex tests and lest the simple one.—

**Comment by jgrzebyta** [comment]
On 5 October 2016 at 19:05, pulquero <notifications@github.com> wrote:

> Most spin magic properties evaluate in the other direction:
> ("Abf1" <http://www.openrdf.org/contrib/lucenesail#allMatches> <
> http://www.openrdf.org/contrib/lucenesail#score>) <http://www.openrdf.org/
> contrib/lucenesail#search> (?pred ?score)
>
> cf:
>
> (?query "this" owl:Thing) spin:construct (?s ?p ?o)
>

So that why it did not work. :-)  I am picking up all useful tests into
separate and cleaner branch and will modify the tests code due to your
explanation.


>
> However the spif functions are all the other way round. jena property
> functions are a mixture. I don't have any preference myself, is one way
> more readable than the other? Any other consideration?
>
>
Spin is a well standardised machinery and although I do not use it (yet)
IMHO it is worth to follow its rules.

**Comment by jgrzebyta** [comment]
There is a problem with compiling `rdf4j-sail-spin` module because of missing dependencies:

```
org/eclipse/rdf4j/sail/spin/SpinSailConnection.java:[75,40] error: package org.eclipse.rdf4j.sail.evaluation does not exist
org/eclipse/rdf4j/sail/SailConnectionQueryPreparer.java:[22,40] error: package org.eclipse.rdf4j.sail.evaluation does not exist
org/eclipse/rdf4j/sail/spin/SpinSailConnection.java:[136,26] error: cannot find symbol
 class SpinSailConnection
org/eclipse/rdf4j/sail/spin/SpinSailConnection.java:[208,9] error: cannot find symbol
 class SpinSailConnection
org/eclipse/rdf4j/sail/SailConnectionQueryPreparer.java:[43,20] error: cannot find symbol
5 errors 
```

**Comment by pulquero** [comment]
SailConnectionQueryPreparer and friends are prime candidates for being moved out into queryalgebra-evaluation.
 

    On Thursday, 6 October 2016, 10:17, Jacek Grzebyta <notifications@github.com> wrote:
 

 There is a problem with compiling rdf4j-sail-spin module because of missing dependencies:org/eclipse/rdf4j/sail/spin/SpinSailConnection.java:[75,40] error: package org.eclipse.rdf4j.sail.evaluation does not exist
org/eclipse/rdf4j/sail/SailConnectionQueryPreparer.java:[22,40] error: package org.eclipse.rdf4j.sail.evaluation does not exist
org/eclipse/rdf4j/sail/spin/SpinSailConnection.java:[136,26] error: cannot find symbol
 class SpinSailConnection
org/eclipse/rdf4j/sail/spin/SpinSailConnection.java:[208,9] error: cannot find symbol
 class SpinSailConnection
org/eclipse/rdf4j/sail/SailConnectionQueryPreparer.java:[43,20] error: cannot find symbol
5 errors

**Comment by pulquero** [comment]
Tests now merged in (btw the spin and the tuple function tests were the wrong way round).
#220 and #235 now essentially fixed.
Spin integration up next.

**Comment by jeenbroekstra** [comment]
What's the status of this PR? Ready for final review, test, and merge? Or is the "spin integration" you mentioned before part of this effort as well? 

Also would like to hear a bit more about what, exactly, is being addressed here. "Search improvements" is rather broad, and I get the feeling that the changes here are also more general than just fixing issues #220 and #235 (but feel free to correct me if I'm wrong about that).

**Comment by pulquero** [comment]
Still work in progress. To fix #220 and #235 the lucene queries have to be evaluated 'late', when the rest of the query has been evaluated and the input vars are bound. This is hard as-is since query evaluation is delegated to the base sail. This is a similar situation with the SPIN inferencer, and we can use the same solution, namely tuplefunctions. Currently, the PR has a TupleFunction for text queries but not spatial searches and some of the code duplicates that of the spin sail (as a first-pass I only did a proof-of-concept). So, atm we have a proof-of-concept and to do is a 2nd pass to share common code between spin and lucene where possible, and add support for spatial searches.

**Comment by jgrzebyta** [comment]
I did reverse dependencies analysis and I found that module `rdf4j-sail-base` dependency clash might be fixed by one of those options:
1. simple rule not to call `rdf4j-sail-api` directly. 
2. merge both modules: `rdf4j-sail-api` and `rdf4j-sail-base`


The facts are:
* In **tests** that module is used by `rdf4j-sail-memory`
* In **runtime** is used also only by `rdf4j-sail-memory`
* In the default scope used only by 3 modules: `rdf4j-sail-memory`, `rdf4j-sail-lucene-api` and `rdf4j-sail-nativerdf`.

I am pro the second fix. Mainly because that module contains a lot of interfaces + theirs core implementations.

If you want to get visualisation of that it is [on my googledrive](https://drive.google.com/open?id=0B9vmnMuEyN3VNmt0V1REUG4ySnM).

**Comment by jeenbroekstra** [comment]
@jgrzebyta can you elaborate on what this dependency clash is that you're talking about - that is, what exactly is causing it? I haven't looked at this PR in detail lately, but I don't see why there should be a clash: sail-base depends on sail-api, and not the other way around. This seems straightforward.

I'm not in favor of the second option you mention. First of all this suddenly makes the sail-api module very dependency-heavy (sail-base depends on a lot of other RDF4J and third-party modules), which makes life harder for third-party sail developers that don't necessarily want to use the other RDF4J stuff. Apart from that, I'm not quite sure what the backward-compatibility consequences of merging modules would be: arguably it would require that we do a major version update. Doesn't mean we can't do it of course, but I'd _hesitate_ about it, at least.

**Comment by jgrzebyta** [comment]
The dependency clash is within `rdf4j-sail-spin` it misses few classes from `rd4j-sail-base` on both default and test scopes.

If sail-base has lots of dependencies than indeed it is better to merge with the api.

I will add missing rdf4j-sail-base into rdf4j-sail-spin and try to run the suit tests.

**Comment by jgrzebyta** [comment]
@pulquero  
Still tests do not work. I found a lot of errors:
```
10:16:12.278 [main] DEBUG o.e.r.q.a.e.i.ConstantOptimizer Failed to evaluate UnaryValueOperator with a constant argument
org.eclipse.rdf4j.query.algebra.evaluation.ValueExprEvaluationException: null
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.evaluate(SimpleEvaluationStrategy.java:1300) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.evaluate(SimpleEvaluationStrategy.java:1086) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.ConstantOptimizer$ConstantVisitor.meetUnaryValueOperator(ConstantOptimizer.java:212) ~[classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:205) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Datatype.visit(Datatype.java:36) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.ExtensionElem.visitChildren(ExtensionElem.java:64) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:247) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.ExtensionElem.visit(ExtensionElem.java:57) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Extension.visitChildren(Extension.java:100) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetUnaryTupleOperator(AbstractQueryModelVisitor.java:687) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:241) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Extension.visit(Extension.java:92) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:80) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Filter.visitChildren(Filter.java:62) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetUnaryTupleOperator(AbstractQueryModelVisitor.java:687) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:253) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Filter.visit(Filter.java:54) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:100) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetBinaryTupleOperator(AbstractQueryModelVisitor.java:607) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:541) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Union.visit(Union.java:58) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:80) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetUnaryTupleOperator(AbstractQueryModelVisitor.java:687) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:517) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.Slice.visit(Slice.java:86) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.UnaryTupleOperator.visitChildren(UnaryTupleOperator.java:80) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:475) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.QueryRoot.visit(QueryRoot.java:47) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.ConstantOptimizer.optimize(ConstantOptimizer.java:72) [classes/:na]
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.evaluateInternal(SailSourceConnection.java:231) [classes/:na]
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.evaluate(AbstractSailConnection.java:261) [classes/:na]
	at org.eclipse.rdf4j.sail.helpers.SailConnectionWrapper.evaluate(SailConnectionWrapper.java:95) [classes/:na]
	at org.eclipse.rdf4j.sail.inferencer.InferencerConnectionWrapper.evaluate(InferencerConnectionWrapper.java:118) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.evaluateInternal(SpinSailConnection.java:239) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.evaluate(SpinSailConnection.java:175) [classes/:na]
	at org.eclipse.rdf4j.sail.SailConnectionBooleanQuery.evaluate(SailConnectionBooleanQuery.java:48) [classes/:na]
	at org.eclipse.rdf4j.spin.function.SpinFunction.evaluate(SpinFunction.java:73) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.evaluate(SimpleEvaluationStrategy.java:1669) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.evaluate(SimpleEvaluationStrategy.java:1122) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.evaluate(SimpleEvaluationStrategy.java:1734) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.evaluate(SimpleEvaluationStrategy.java:1131) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategy.isTrue(SimpleEvaluationStrategy.java:1987) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.FilterIterator.accept(FilterIterator.java:87) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.FilterIterator.accept(FilterIterator.java:23) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:84) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:47) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:68) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.MultiProjectionIterator.getNextElement(MultiProjectionIterator.java:87) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.MultiProjectionIterator.getNextElement(MultiProjectionIterator.java:24) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.lookAhead(LookAheadIteration.java:92) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.LookAheadIteration.hasNext(LookAheadIteration.java:52) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:81) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:47) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63) [classes/:na]
	at org.eclipse.rdf4j.sail.base.SailClosingIteration.hasNext(SailClosingIteration.java:89) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63) [classes/:na]
	at org.eclipse.rdf4j.sail.helpers.SailBaseIteration.hasNext(SailBaseIteration.java:48) [classes/:na]
	at org.eclipse.rdf4j.query.algebra.evaluation.iterator.QueryContextIteration.hasNext(QueryContextIteration.java:40) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.FilterIteration.findNextElement(FilterIteration.java:81) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.FilterIteration.hasNext(FilterIteration.java:47) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.ConvertingIteration.hasNext(ConvertingIteration.java:68) [classes/:na]
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:63) [classes/:na]
	at org.eclipse.rdf4j.query.QueryResults.report(QueryResults.java:176) [classes/:na]
	at org.eclipse.rdf4j.sail.SailConnectionGraphQuery.evaluate(SailConnectionGraphQuery.java:148) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinInferencing.checkConstraint(SpinInferencing.java:103) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.checkConstraint(SpinSailConnection.java:640) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.checkConstraints(SpinSailConnection.java:632) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.applyRulesInternal(SpinSailConnection.java:461) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.applyRules(SpinSailConnection.java:403) [classes/:na]
	at org.eclipse.rdf4j.sail.inferencer.fc.AbstractForwardChainingInferencerConnection.doInferencing(AbstractForwardChainingInferencerConnection.java:172) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSailConnection.doInferencing(SpinSailConnection.java:392) [classes/:na]
	at org.eclipse.rdf4j.sail.inferencer.fc.AbstractForwardChainingInferencerConnection.flushUpdates(AbstractForwardChainingInferencerConnection.java:113) [classes/:na]
	at org.eclipse.rdf4j.sail.inferencer.InferencerConnectionWrapper.commit(InferencerConnectionWrapper.java:105) [classes/:na]
	at org.eclipse.rdf4j.sail.spin.SpinSail.initialize(SpinSail.java:145) [classes/:na]
	at org.eclipse.rdf4j.sail.helpers.SailWrapper.initialize(SailWrapper.java:99) [classes/:na]
	at org.eclipse.rdf4j.sail.lucene.LuceneSail.initialize(LuceneSail.java:337) [classes/:na]
	at org.eclipse.rdf4j.repository.sail.SailRepository.initializeInternal(SailRepository.java:151) [classes/:na]
	at org.eclipse.rdf4j.repository.base.AbstractRepository.initialize(AbstractRepository.java:31) [classes/:na]
	at org.eclipse.rdf4j.sail.lucene.AbstractLuceneSailSpinTest.setUp(AbstractLuceneSailSpinTest.java:70) [classes/:na]
```

**Comment by ansell** [comment]
Maven does not inherit dependencies for modules inherited in the "test" scope. You need to also inherit any of the dependencies into test scope explicitly in any modules that depend on them.

**Comment by pulquero** [comment]
Late evaluation of the geo stuff needs more work than expected. So I'm gonna postpone that for another issue. This is now ready for final review, scope is late evaluation of full text queries only.

**Comment by jgrzebyta** [comment]
@pulquero. Is it possible to publish PR with fix for the older syntax
because it worked?

If you want I can help you and make unit tests for geo data.

**Comment by pulquero** [comment]
I'm actually working on the geo stuff currently, but dont know if it makes sense to do it as a separate issue/pr or not, to prevent holding up the current fixes for search. Help with the unit tests would be great. My currently working branch is https://github.com/pulquero/rdf4j/tree/issues/%23220-geo.

**Comment by jeenbroekstra** [comment]
Without knowing too much about what "the geo stuff" is, I'd say doing it as a separate issue sounds good. This PR has already been open for quite a while and I have a feeling there's quite a lot being fixed, refactored, and improved already. It's probably better to identify further issues as separate improvements, and log them (and work on them) as such. 

Btw you have a conflict, caused by my recent merge of #657 . May want to sync with the master branch.

File: core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java [hunk 9]
```diff
@@ -0,0 +1,57 @@
...
+ * are made available under the terms of the Eclipse Distribution License v1.0
+ * which accompanies this distribution, and is available at
+ * http://www.eclipse.org/org/documents/edl-v10.php.
+ *******************************************************************************/
+package org.eclipse.rdf4j.query.algebra.evaluation;
+
+import java.util.HashMap;
+import java.util.Map;
+
+public class QueryContext {
```
Comment (jeenbroekstra) [inline core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java]: What is a `QueryContext`? We should probably add some javadoc explaining the purpose of this interface.

File: core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java [hunk 10]
```diff
@@ -0,0 +1,57 @@
+/*******************************************************************************
+ * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
```
Comment (jeenbroekstra) [inline core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java]: Incorrect copyright header.

File: testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailSpinTest.java [hunk 11]
```diff
@@ -0,0 +1,337 @@
+/*******************************************************************************
+ * Copyright (c) 2016 Eclipse RDF4J contributors, Aduna, and others.
```
Comment (jeenbroekstra) [inline testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailSpinTest.java]: Incorrect copyright header.

File: testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java [hunk 12]
```diff
@@ -1,10 +1,10 @@
-/*******************************************************************************
- * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
+/**
+ * Copyright (c) 2016 Eclipse RDF4J contributors.
  * All rights reserved. This program and the accompanying materials
  * are made available under the terms of the Eclipse Distribution License v1.0
  * which accompanies this distribution, and is available at
  * http://www.eclipse.org/org/documents/edl-v10.php.
- *******************************************************************************/
+ */
```
Comment (jeenbroekstra) [inline testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java]: This is actually incorrect as well - the template we use includes a full line of asterisks at the beginning and the end of the license header.

File: testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/yeastract_raw.ttl [hunk 13]
```diff
@@ -0,0 +1,1436 @@
+
+<urn:raw:yeastract#Yeast_id> <http://www.w3.org/2000/01/rdf-schema#label> "yeast_id" ;
```
Comment (jeenbroekstra) [inline testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/yeastract_raw.ttl]: Where does this test data come from? If it's third-party we'll need to know its license, and log a CQ for its inclusion.

File: core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java (hunk 10 above)
Comment (jeenbroekstra) [inline core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java]: Actually forget that, I just noticed that this interface is not new, but moved. So the old copyright headers stays.

File: core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java [hunk 14]
```diff
@@ -0,0 +1,57 @@
...
+
+	private final Map<String, Object> attributes = new HashMap<>();
+
+	private QueryContext previous;
+
+	public QueryContext() {
+	}
+
+	public QueryContext(QueryPreparer qp) {
+		setAttribute(QUERY_PREPARER_ATTRIBUTE, qp);
```
Comment (jeenbroekstra) [inline core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/QueryContext.java]: Why the roundabout way with `setAttribute`? Wouldn't be simpler to have a `getQueryPreparer` method?

File: testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/yeastract_raw.ttl (hunk 13 above)
Comment (jgrzebyta) [inline testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/yeastract_raw.ttl]: I will take that because I produced the testing dataset from third-party community.

File: testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java (hunk 12 above)
Comment (pulquero) [inline testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java]: It doesn't, I just checked: https://github.com/eclipse/rdf4j/blob/master/eclipse-settings/codetemplates.xml

Comment (jeenbroekstra) [inline testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java]: Well I feel silly now. Let me check what the "correct" (= used in most files) setting is and get back to you.

Comment (jeenbroekstra) [inline testsuites/lucene/src/main/java/org/eclipse/rdf4j/sail/lucene/AbstractLuceneSailTest.java]: Logged an issue for this: #662 . I'll upload a fixed template and later do some cleanup of existing code. Don't worry too much about it in this particular PR.

**Comment by jeenbroekstra** [comment]
I just realized that although I approved the changes by @pulquero , we cannot merge this until the status of the test data has been clarified.

File: testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/yeastract_raw.ttl (hunk 13 above)
Comment (jeenbroekstra) [inline testsuites/lucene/src/main/resources/org/eclipse/rdf4j/sail/yeastract_raw.ttl]: As discussed: we need to sort out where this data comes from before we can merge this PR in. Just adding a comment to allow me to mark the PR as "needs changes".

**Comment by jgrzebyta** [comment]
Apologies for late. I have tried to contact with Yeastract team but with no
success. Because there is not license information about the data on the
project web page I have just added the copyright line plus citations from
"how to cite us" sub web page. Everything in
7e959ce19623ac49c7730e788a8c5bca4d4af552.

**Comment by jeenbroekstra** [comment]
@jgrzebyta thanks for looking into this, but unfortunately just including the copyright notice won't be good enough. I'll check with the legal team but if there are no license terms available for the data we can probably not include it. 

I'll launch a CQ request and see what the legal team have to say about it. 

In the mean time: how much work would it be to replace this data with something of our own making (or something with clear license terms - e.g. DBPedia data is shared under CC-SA, which probably makes it ok for reuse)?

**Comment by pulquero** [comment]
It will be interesting to see what the legal team make of it. As an academic work done at a national university it should be free as beer to use. It is kind of BSD style - if you use it you must cite it. The knowledge/data is public domain, the only thing I believe is copyright able is the format it is stored in. I await the outcome with interest.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jeen Broekstra <notifications@github.com> Date: 28/11/2016  21:03  (GMT+00:00) To: eclipse/rdf4j <rdf4j@noreply.github.com> Cc: pulquero <mj_hale@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [eclipse/rdf4j] Fix #220: search improvements (#584) 
@jgrzebyta thanks for looking into this, but unfortunately just including the copyright notice won't be good enough. I'll check with the legal team but if there are no license terms available for the data we can probably not include it.
I'll launch a CQ request and see what the legal team have to say about it.
In the mean time: how much work would it be to replace this data with something of our own making (or something with clear license terms - e.g. DBPedia data is shared under CC-SA, which probably makes it ok for reuse)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eclipse/rdf4j","title":"eclipse/rdf4j","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/eclipse/rdf4j"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jeenbroekstra in #584: @jgrzebyta thanks for looking into this, but unfortunately just including the copyright notice won't be good enough. I'll check with the legal team but if there are no license terms available for the data we can probably not include it. \r\n\r\nI'll launch a CQ request and see what the legal team have to say about it. \r\n\r\nIn the mean time: how much work would it be to replace this data with something of our own making (or something with clear license terms - e.g. DBPedia data is shared under CC-SA, which probably makes it ok for reuse)? "}],"action":{"name":"View Pull Request","url":"https://github.com/eclipse/rdf4j/pull/584#issuecomment-263393409"}}}

**Comment by jeenbroekstra** [comment]
CQ filed: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12328

**Comment by jgrzebyta** [comment]
I created the RDF myself. It is a part of our academic project and the RDF
file itself is a 'transcription' of TFConsensusList_20130918.transfac.gz
file from http://yeastract.com/download.php. It was made using apache's
any23. Quite complex. I will replace it by DBpedia data.

**Comment by jeenbroekstra** [comment]
Replacing with DBPedia data won't fix the fundamental problem that we're using a third-party resource, for which we will need to obtain legal approval. For DBPedia data this may be easier to do, but if at all possible I'd really prefer that we just create our own (synthesized) test data, so that there is no question about its ownership, and no bureaucractic holdup.

**Comment by jgrzebyta** [comment]
So I will replace that by synthetic dataset.

**Comment by jeenbroekstra** [comment]
Thanks @jgrzebyta that would be great, and sorry to be a pain about this. Eclipse due diligence is good to have in general, but sometimes a pain in the arse.

**Comment by jgrzebyta** [comment]
@jeenbroekstra , @pulquero  All done in a777c6922ac746fc7608f9fc6393bf25024d521f

**Comment by jeenbroekstra** [comment]
Thanks, that's great. I guess it's up to @pulquero to merge your changes into his branch, so that it shows up in this PR?

**Comment by pulquero** [comment]
Good point! Done.
