### PR TITLE
GH-3935: Remove SmartTransactionObject from TransactionObject

### LINKED ISSUE #3935: Transaction fails with UnexpectedRollBackException for SmartTransactionObject
### Problem description

As the `TransactionObject implements SmartTransactionObject` the default `TransactionStatus` is `RollbackOnly` and as we use it, an `UnexpectedRollBackException` occurs.

### Preferred solution

As a solution we fixed the problem and will open a PR for that.

### Are you interested in contributing a solution yourself?

Yes

### Alternatives you've considered

_No response_

### Anything else?

Also extended the `Expressions.java` with some more overloading functions.

### PR DESCRIPTION
**Pull request by maxstolze**
GitHub issue resolved: #3935 

Briefly describe the changes proposed in this PR:

CherryPick to fix #3935 for a 4.0.4 Release

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

File: core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java [hunk 1]
```diff
@@ -318,6 +325,14 @@ public static Expression<?> notEquals(Operand left, Operand right) {
...
 	}
 
+	public static Expression<?> notEquals(Variable left, RdfValue right) {
+		return binaryExpression(BinaryOperator.NOT_EQUALS, left, right);
+	}
+
+	public static Expression<?> notEquals(Variable left, IRI right) {
+		return binaryExpression(BinaryOperator.NOT_EQUALS, left, iri(right));
+	}
+
```
Comment (hmottestad) [inline core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java:335]: Are these changes required for the fix in TransactionObject?

File: spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilder.java [hunk 2]
```diff
@@ -55,6 +56,11 @@ public RelationMapBuilder(RDF4JTemplate rdf4JTemplate, RdfPredicate predicate) {
 		this.predicate = predicate;
 	}
 
+	public RelationMapBuilder(RDF4JTemplate rdf4JTemplate, IRI predicate) {
+		this.rdf4JTemplate = rdf4JTemplate;
+		this.predicate = iri(predicate);
+	}
+
```
Comment (hmottestad) [inline spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilder.java:63]: Are these changes required for the fix in TransactionObject?

File: spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/ServiceLayerTests.java [hunk 3]
```diff
@@ -66,6 +69,7 @@ public void testCreatePaintingWithoutArtist() {
 				null));
 	}
 
+	// TODO
```
Comment (hmottestad) [inline spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/ServiceLayerTests.java:72]: Why is there a TODO comment here?

File: spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/tx/TransactionObject.java [hunk 4]
```diff
@@ -22,7 +22,7 @@
  * @author ameingast@gmail.com
  * @author Florian Kleedorfer
  */
-public class TransactionObject implements SmartTransactionObject {
```
Comment (hmottestad) [inline spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/tx/TransactionObject.java:25]: @jeenbroekstra The spring somponents module is not part of the core module. We haven't added the japicmp build plugin to the pom files either. Does that entail that we don't follow semantic versioning for the spring components?

File: core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java (hunk 1 above)
Comment (maxstolze) [reply core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java:335]: As long as the issues in the 4.1.0-M1 version are present, we desperately need these changes already in 4.0.4 for our project.

File: spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilder.java (hunk 2 above)
Comment (maxstolze) [reply spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/dao/support/RelationMapBuilder.java:63]: As long as the issues in the 4.1.0-M1 version are present, we desperately need these changes already in 4.0.4 for our project.

File: spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/ServiceLayerTests.java (hunk 3 above)
Comment (fkleedorfer) [reply spring-components/rdf4j-spring/src/test/java/org/eclipse/rdf4j/spring/dao/support/ServiceLayerTests.java:72]: I forgot to remove it.

File: spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/tx/TransactionObject.java (hunk 4 above)
Comment (jeenbroekstra) [reply spring-components/rdf4j-spring/src/main/java/org/eclipse/rdf4j/spring/tx/TransactionObject.java:25]: We do - we follow semantic versioning for the entire framework. 

I think we can let this slide "just this once" since the component is so new and is basically still in experimental stage. Might be good to explicitly mark it as such though.

File: core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java (hunk 1 above)
Comment (jeenbroekstra) [reply core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/constraint/Expressions.java:335]: @maxstolze but these specific changes have nothing to do with the fix that you need. They're just a couple of utility functions you added.

**Review by jeenbroekstra — CHANGES_REQUESTED** [review]
There are some problems with adding these changes in a patch release: they are backward incompatible, for one thing, and for another some of these changes seem unrelated to the actual problem you're trying to solve.

Given that the spring component is still very new I think we can let that partially slide this once, but I would  ask that you make the following changes:

- [ ] mark the main classes and interfaces of the spring module using our `@Experimental` annotation
- [ ] remove unrelated changes to the SPARQLBuilder component

**Comment by maxstolze** [comment]
Will add missing @Experimental tags based on the classes and interfaces used in `rdf4j-spring-demo`

**Review by jeenbroekstra — APPROVED** [review]
Happy with this - fire it up!
